#!/bin/sh
# SPDX-License-Identifier: Apache-2.0
#
# Register CleanX in LuCI.
# Safe for OpenWrt 24.x/opkg and OpenWrt 25.x/apk.

uci -q batch <<'EOF'
set luci.themes.CleanX=/luci-static/cleanx
set luci.themes.UniWRT=/luci-static/cleanx
set luci.themes.X1Wrt=/luci-static/cleanx
commit luci
EOF

CURRENT_MEDIA="$(uci -q get luci.main.mediaurlbase || true)"

case "$CURRENT_MEDIA" in
	""|"/luci-static/bootstrap"|"/luci-static/uniwrt"|"/luci-static/x1wrt"|"/luci-static/cleanx")
		uci -q set luci.main.mediaurlbase='/luci-static/cleanx'
		uci -q commit luci
	;;
esac

rm -f /tmp/luci-indexcache.*
rm -rf /tmp/luci-modulecache/

exit 0
