#!/bin/sh

# Keep the user's selected theme during package upgrades.
[ "$PKG_UPGRADE" = 1 ] && exit 0

uci -q get luci.themes.UniWRT >/dev/null 2>&1 || \
uci batch <<-EOT
	set luci.themes.UniWRT='/luci-static/uniwrt'
	set luci.main.mediaurlbase='/luci-static/uniwrt'
	commit luci
EOT

exit 0
